name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  create:
    branches: [master]
    tags: ['**']

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies using pip
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install pd-parser
      run: pip install --no-deps .
    - name: Run pytest
      run: |
        python -m pytest . --cov=pd_parser/tests/ --cov-report=xml --cov-config=setup.cfg --verbose
    - name: Run style & documentation tests
      if: "matrix.os == 'ubuntu-latest'"
      run: make pep
    - name: Upload coverage stats to codecov
      if: "matrix.os == 'ubuntu-latest'"
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
