name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  create:
    branches: [master]
    tags: ['**']

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies using pip
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Display versions and environment information
      run: |
        echo $TZ
        date
        python --version
        which python
    - name: Install pd-parser
      run: pip install --no-deps .
    - name: Set up Node.js
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12
    - name: Install BIDS validator (stable)
      if: "matrix.os != 'ubuntu-latest'"
      run: |
        npm install -g bids-validator
    - name: Install BIDS validator (master)
      if: "matrix.os == 'ubuntu-latest'"
      run: |
        cd ..
        git clone --depth 1 https://github.com/bids-standard/bids-validator
        cd bids-validator
        git checkout master
        yarn
        echo "::add-path::$(pwd)/bids-validator/bin"
        cd ../pd-parser
    - name: Display versions and environment information
      run: |
        echo $TZ
        date
        echo "npm"; npm --version
        echo "node"; node --version
        echo "bids-validator"; bids-validator --version
        python --version
        which python
        mne sys_info
    - name: Install pd-parser
      run: pip install --no-deps .
    - name: Run pytest
      run: |
        echo "bids-validator"; bids-validator --version
        python -m pytest . --cov=pd_parser/tests/ --cov-report=xml --cov-config=setup.cfg --verbose --ignore mne-python
    - name: Run style & documentation tests
      if: "matrix.os == 'ubuntu-latest'"
      run: make pep
    - name: Upload coverage stats to codecov
      if: "matrix.os == 'ubuntu-latest'"
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
